// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadTextFile(arg1) {
  return window['go']['main']['App']['LoadTextFile'](arg1);
}

export function OpenVault() {
  return window['go']['main']['App']['OpenVault']();
}
